name: "Check code"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: "Run cargo check on the whole project"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup the Rust stable toolchain"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
          override: true

      - name: "Checkout the repository"
        uses: actions/checkout@v2

      - name: "Run cargo check"
        uses: actions-rs/cargo@v1
        with:
          command: "check"

